[theme]
# Primary accent color for interactive elements.
primaryColor = "#f66b69"

# Background color for the main content area.
backgroundColor = "#143d8c"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Color used for almost all text.
textColor = "#fff"
