[theme]
# Primary accent color for interactive elements.
primaryColor = "#b01f24"

# Background color for the main content area.
backgroundColor = "#003f88"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Color used for almost all text.
textColor = "#fff"
